spring:
  datasource:
    mysql:
      name: mysql
      url: jdbc:mysql://localhost:3306/test?charset=utf8&serverTimezone=GMT%2B8&autoReconnect=true&failOverReadOnly=false
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
      druid:
        filters: stat
        maxActive: 20
        initialSize: 10
        maxWait: 9000
        minIdle: 10
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 160000
        maxEvictableIdleTimeMillis: 230000
        validationQuery: select 1
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
        keepAlive: true

  jpa:
    #database: mysql
    show-sql: true
    open-in-view: true
    properties:
      hibernate:
      #format_sql: true
      #enable_lazy_load_no_trans: true
    hibernate:
      format_sql: true
      ddl-auto: update
      naming:
        #implicit_naming_strategy:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        #database-platform: org.hibernate.dialect.MySQL5InnoDBDialect