info:
  author: huss
  date: 2020年10月24日
  remark: springboot web框架测试01
  my-server-name: spring-simple-web1

server:
  port: 8084

#spring
spring:
  application:
    name: ${info.my-server-name}
  profiles:
    active: dev
  devtools:
    restart:
      enabled: true
#  main:
#    allow-bean-definition-overriding: true