server:
  port: 8084
  session-timeout: 30
  servlet:
    context-path: /simple/web1
    encoding:
      charset: UTF-8
      force: true
  tomcat:
    uri-encoding: UTF-8
    threads:
      max: 800
spring:

  jackson:
    data-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  aop:
    auto: true
    proxy-target-class: true
  http:
    encoding:
      enable: true

  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
