info:
  author: huss
  date: 2020年5月20日
  remark: spring oauth2
  my-server-name: spring-web-auth

server:
  port: 8083

#spring
spring:
  application:
    name: ${info.my-server-name}
  profiles:
    active: dev
  devtools:
    restart:
      enabled: true

    