spring:
  aop:
    proxy-target-class: true
    auto: true
  datasource:
    primary:
      name: mysql
      url: jdbc:mysql://localhost:3306/test?charset=utf8&serverTimezone=GMT%2B8&autoReconnect=true&failOverReadOnly=false
      username: root
      password: root123456
      driver-class-name: com.mysql.cj.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
      filters: stat,wall,log4j2
      maxActive: 10
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 100000
      # 最大7小时
      maxEvictableIdleTimeMillis: 900000
      # 最小 30分钟
      minEvictableIdleTimeMillis: 600000
      validationQuery: SELECT 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      keepAlive: true
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500

    jpa:
    #database: mysql
    show-sql: true
    open-in-view: true
    properties:
      hibernate:
      #format_sql: true
      #enable_lazy_load_no_trans: true
    hibernate:
      format_sql: true
      ddl-auto: update
      naming:
        #implicit_naming_strategy:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        #database-platform: org.hibernate.dialect.MySQL5InnoDBDialect