spring:
  autoconfigure:
    exclude:
      - com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
  aop:
    proxy-target-class: true
    auto: true
  datasource:
    primary:
      name: mysql
      url: jdbc:mysql://localhost:3306/test?charset=utf8&serverTimezone=GMT%2B8&autoReconnect=true&failOverReadOnly=false
      username: root
      password: root123456
      driver-class-name: com.mysql.cj.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
      filters: stat,wall,log4j2
      maxActive: 10
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 100000
      # 最大7小时
      maxEvictableIdleTimeMillis: 900000
      # 最小 30分钟
      minEvictableIdleTimeMillis: 600000
      validationQuery: SELECT 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      keepAlive: true
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
    test2:
      name: mysql
      url: jdbc:mysql://localhost:3306/test2?charset=utf8&serverTimezone=GMT%2B8&autoReconnect=true&failOverReadOnly=false
      username: root
      password: root123456
      driver-class-name: com.mysql.cj.jdbc.Driver
      #      type: com.zaxxer.hikari.HikariDataSource
      #      # 连接只读数据库时配置为true， 保证安全
      #      read-only: true
      #      # 等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQLException， 缺省:30秒 30000
      #      connection-timeout: 60000
      #      # 一个连接idle状态的最大时长（毫秒），超时则被释放（retired），缺省:10分钟 600000
      #      idle-timeout: 60000
      #      # 一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），缺省:30分钟，建议设置比数据库超时时长少30秒 1800000
      #      max-lifetime: 90000
      #      # 连接池中允许的最大连接数。缺省值：10
      #      maximum-pool-size: 10
      #      minimum-idle: 1

      type: com.alibaba.druid.pool.DruidDataSource
      filters: stat,wall,log4j2
      maxActive: 10
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 100000
      # 最大 900000
      maxEvictableIdleTimeMillis: 900000
      # 最小 600000
      minEvictableIdleTimeMillis: 600000
      validationQuery: SELECT 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      keepAlive: true
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
    jpa:
    #database: mysql
    show-sql: true
    open-in-view: true
    properties:
      hibernate:
      #format_sql: true
      #enable_lazy_load_no_trans: true
    hibernate:
      format_sql: true
      ddl-auto: update
      naming:
        #implicit_naming_strategy:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        #database-platform: org.hibernate.dialect.MySQL5InnoDBDialect